[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
async-trait = "0.1.83"
serenity = "0.12.2"
env_logger = "0.11.5"
poise = "0.6.1"
dotenv = "0.15"
log = "0.4.22"
